# Generated by Django 3.0.8 on 2020-08-01 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
