# Generated by Django 3.0.8 on 2020-08-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20200801_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
